#!/usr/bin/bash
lib_path="${IO_LIB}"
if [ $1 = "-I" ]; then
    echo -I${IO_LIB}/include
elif [ $1 = "-L" ]; then
    str="-L${IO_LIB}/lib"

    for io in io oi; do
        while read line; do
            str="${str} -l${io}${line}"
        done < ${lib_path}/${io}_lib_list
    done
    while read line; do
        str="${str} -ltu${line}"
    done < ${lib_path}/tu_lib_list
    echo ${str}
fi

