#!/usr/bin/bash
lib_path="${HOME}/root_macros/io_lib"
if [ $1 = "-I" ]; then
    echo -I${HOME}/root_macros/io_lib/include
elif [ $1 = "-L" ]; then
    str="-L${HOME}/root_macros/io_lib/lib"

    for io in io oi; do
        while read line; do
            str="${str} -l${io}${line}"
        done < ${lib_path}/${io}_lib_list
    done
    echo ${str}
fi

